### ISSUE TITLE
Please remove office email IDs of Infosys , this is published without authorization

### ISSUE THREAD

**Issue by kkshivnarain** [srini26/MLAI#1]

**Comment by srini26** [comment]
Please check and let me know.

**Comment by kkshivnarain** [comment]
No, I can see my email, my name is Kamlesh_kumar, please remove my ID. I am following this link to check
https://github.com/srini26/MLAI/blob/3bca3b1fc197128a3d7516fd27a160e03ada6cad/StatisticsEssential/ML%2BC9.csv
